// pages/navbar.tsx
import styles from '../styles/Navbar.module.css'

export default function NavBar() {
    return (
        <div className={styles.navWrapper}>
            <nav className={`${styles.navCommon} ${styles.navMain}`}>
                <ul>
                    <li><a href="/">Home</a></li>
                    <li><a href="https://www.linkedin.com/in/lrjcostello/">LinkedIn</a></li>
                    <li><a href="https://github.com/lolletsoc">GitHub</a></li></ul>
            </nav>
        </div>
    )
}

// src/lib/components/NavBar.svelte
<div class="mx-auto flex justify-center bg-black">
    <nav>
        <ul class="btn-group [&_li]:px-4 text-white">
            <li><a class="btn" href="/">Home</a></li>
            <li><a class="btn" href="https://www.linkedin.com/in/lrjcostello/">LinkedIn</a></li>
            <li><a class="btn" href="https://github.com/lolletsoc">GitHub</a></li>
        </ul>
    </nav>
</div>
